### ISSUE TITLE
nargs('+')  when inputting a char display 43 instead of one or more.

### ISSUE THREAD

**Issue by phforest** [dgrine/Argo#1]
```/////////////////////////////////////////////
struct Configuration
{
    std::vector< std::string > input_files;
};

int main(int argc, char *argv[])
{
    Configuration config;
    argo::Arguments args;

    argo::handler::Option option{"--input-file"};
    option.help("Numbers to count");
    option.required().nargs('+').action( argo::action::store( config.input_files  ));
    args.add(option);
    const auto result = args.parse(argc, argv);
    if (!result.success)
    {
        std::cerr << "Error: " << result.message << std::endl;
        return 1;
    }
}
/////////////////////////////////////////////
```
result:
=======================
...
   --input-file                                        [required][43 arguments]
        Numbers to count
=======================
it works if it's a string.

Probably better to have to overload:
nargs( int , int )
nargs( char )  '+' , '*'

**Comment by dgrine** [comment]
There are two calls to nargs:

```
 Option &nargs(const unsigned count);
Option &nargs(const std::string &type);
```

Unfortunately, adding an overload on `char` would result in an ambiguity error due to the presence of the `unsigned` overload. Replacing the `unsigned` version with `char` (to perform additional checks) would limit the number of possible arguments. So in short: I don't think there's an easy way to change this... an unfortunate side-effect from C++'s implicit casting from `char` to `unsigned`.
